### ISSUE TITLE
Wrong import string when generating java code

### ISSUE THREAD

**Issue by Tomschi** [ReoLanguage/ECT#1]
I've installed the tool over the eclipse update site.
When the tool generates java code the following import strings are used:

![java_import](https://user-images.githubusercontent.com/1133900/34639297-92b8c4f4-f2dd-11e7-9241-c195ef588b48.png)

But the package strings of the runtime.jar are:

![runtime_lib](https://user-images.githubusercontent.com/1133900/34639255-ebc4d85e-f2dc-11e7-97b8-f26bd2e27753.png)

So, the code generator is not able to produce compileable code.

**Comment by kasperdokter** [comment]
This repository is not supported, and I have no idea how to fix these imports.
